apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
  labels: 
    app: flaskapp
spec:
  containers:
  - name: flaskapp
    image: jth7947/flaskapp:latest
    ports:
    - containerPort: 5000
  imagePullSecrets:
    - name: regcred
